# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My first Jekyll Website
tagline: Learning development by doing it!
description: > # this means to ignore newlines until "author:"
  Example Jekyll website for the Coding Night Workshop.

author: Kevin Gimbel
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Enter your twitter username or remove my name
twitter_username: _kevinatari

# Enter your GitHub username or remove my name
github_username: kevingimbel

# Build settings
markdown: kramdown
permalink: /:categories/:year/:title

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
